/**
 * Cruise-data freshness report.
 *
 * The sailing catalog is a static snapshot regenerated by the Apify pipeline
 * (`scripts/fetch-apify-data.ts` → `src/data/sailings.json`) and committed.
 * `src/lib/data.ts` hides departed and unpriced rows from the public site at
 * read time, so nothing broken ever ships — but that filtering is silent. Left
 * alone, the snapshot ages: departed rows pile up, the bookable window shrinks,
 * and the deal finders quietly thin out with no error anywhere.
 *
 * This module measures that decay. It reads the raw arrays deliberately —
 * `getSailings()` would hide exactly the rows we are trying to count.
 */

import { sailings as rawSailings } from '@/data/sailings'
import { getTodayInChicago, isBookableSailing } from '@/lib/data'

/** Below this many bookable sailings the deal grids start looking empty. */
const MIN_BOOKABLE = 60

/** Below this many sailings inside 90 days the last-minute page runs dry. */
const MIN_NEAR_TERM = 10

/** A snapshot older than this has missed at least two scrape cycles. */
const MAX_SNAPSHOT_AGE_DAYS = 14

/** Once expired rows are this share of the catalog, it is mostly dead weight. */
const MAX_EXPIRED_SHARE = 0.25

export interface FreshnessReport {
  /** Date the report was evaluated against, YYYY-MM-DD in America/Chicago. */
  today: string
  /** Rows in `sailings.json`, including ones the public site never shows. */
  total: number
  /** Rows the public site will serve right now. */
  bookable: number
  /** Rows whose sail date has passed — filtered out, still in the file. */
  expired: number
  /** Rows with a null/NaN/zero lead price — filtered out, still in the file. */
  unpriced: number
  /** Bookable rows departing within 90 days (what feeds last-minute deals). */
  nearTerm: number
  /** Newest `updated_at` in the catalog, or null if none parse. */
  lastUpdated: string | null
  /** Whole days since `lastUpdated`, or null if unknown. */
  snapshotAgeDays: number | null
  /** True if any threshold tripped — the signal to regenerate the data. */
  needsRefresh: boolean
  /** Human-readable reasons, empty when `needsRefresh` is false. */
  reasons: string[]
}

function daysBetween(fromIso: string, todayYmd: string): number | null {
  const from = Date.parse(fromIso)
  const to = Date.parse(`${todayYmd}T00:00:00Z`)
  if (!Number.isFinite(from) || !Number.isFinite(to)) return null
  return Math.floor((to - from) / 86_400_000)
}

/**
 * Pure, synchronous, no network. Safe to call from a route handler or a script.
 */
export function buildFreshnessReport(): FreshnessReport {
  const today = getTodayInChicago()

  const ninetyOut = new Date(`${today}T00:00:00Z`)
  ninetyOut.setUTCDate(ninetyOut.getUTCDate() + 90)
  const nearTermCutoff = ninetyOut.toISOString().slice(0, 10)

  let bookable = 0
  let expired = 0
  let unpriced = 0
  let nearTerm = 0
  let newestUpdate = ''

  for (const s of rawSailings) {
    const departed = typeof s.sail_date !== 'string' || s.sail_date.slice(0, 10) < today
    const priced = Number.isFinite(s.current_lowest_price) && s.current_lowest_price > 0

    if (departed) expired++
    // Counted separately from `expired` on purpose: a row can be both, and the
    // fix differs — expired rows need a newer scrape, unpriced rows need the
    // price columns investigated.
    if (!priced) unpriced++

    if (isBookableSailing(s, today)) {
      bookable++
      if (s.sail_date.slice(0, 10) <= nearTermCutoff) nearTerm++
    }

    if (typeof s.updated_at === 'string' && s.updated_at > newestUpdate) {
      newestUpdate = s.updated_at
    }
  }

  const lastUpdated = newestUpdate || null
  const snapshotAgeDays = lastUpdated ? daysBetween(lastUpdated, today) : null

  const reasons: string[] = []
  if (rawSailings.length === 0) {
    reasons.push('Catalog is empty — the Apify import produced no sailings.')
  }
  if (bookable < MIN_BOOKABLE) {
    reasons.push(`Only ${bookable} bookable sailings left (want at least ${MIN_BOOKABLE}).`)
  }
  if (nearTerm < MIN_NEAR_TERM) {
    reasons.push(`Only ${nearTerm} sailings inside 90 days (want at least ${MIN_NEAR_TERM}).`)
  }
  if (snapshotAgeDays !== null && snapshotAgeDays > MAX_SNAPSHOT_AGE_DAYS) {
    reasons.push(`Newest record is ${snapshotAgeDays} days old (want under ${MAX_SNAPSHOT_AGE_DAYS}).`)
  }
  if (snapshotAgeDays === null) {
    reasons.push('No usable updated_at timestamp in the catalog — cannot age-check it.')
  }
  if (rawSailings.length > 0 && expired / rawSailings.length > MAX_EXPIRED_SHARE) {
    const pct = Math.round((expired / rawSailings.length) * 100)
    reasons.push(`${pct}% of the catalog has already departed (want under ${Math.round(MAX_EXPIRED_SHARE * 100)}%).`)
  }
  if (unpriced > 0) {
    reasons.push(`${unpriced} sailings have no usable lead price and are hidden from listings.`)
  }

  return {
    today,
    total: rawSailings.length,
    bookable,
    expired,
    unpriced,
    nearTerm,
    lastUpdated,
    snapshotAgeDays,
    needsRefresh: reasons.length > 0,
    reasons,
  }
}
